name: API-test
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  API-test-prep:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        supportedVersion: ["test1", "test2"]

    outputs:
      test: ${{ steps.outputTest.outputs.test}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Reading property files
        continue-on-error: true
        id: json_props
        uses: zoexx/github-action-json-file-properties@1.0.6
        with:
          file_path: "./test.json"

      - name: testing outputs
        id: outputTest
        run: |
          echo "test=${{matrix.supportedVersion}}" >> $GITHUB_OUTPUT

  API-test:
    needs: API-test-prep
    runs-on: ubuntu-latest
    strategy:
      matrix:
        supportedVersion: ["test1", "test2"]

    steps:
      - name: test
        run: |
          echo "test: ${{needs.API-test-prep.outputs.test}}"
