name: BuildAndDeploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  ImageBuildAndPush:
    name: Building Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     context: .
      #     tags: |
      #       balamani3010/athene-test:latest-${{ github.sha }}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      # - name: Build and store
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: false
      #     context: .
      #     tags: |
      #       balamani3010/athene-test:latest-${{ github.sha }}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      #     outputs: type=docker,dest=/tmp/athene-test.tar

      - name: tetsing docker images
        id: test
        run: |
          echo "test=final" >> $GITHUB_OUTPUT

      - name: final
        if: steps.test.outputs.test == ${{ github.sha }}
        run: |
          echo "both are equal"
